import 'package:flutter/material.dart';

@immutable
class AppColorScheme extends ThemeExtension<AppColorScheme> {
  const AppColorScheme._({
    required this.primary,
    required this.onPrimary,
    required this.primaryContainer,
    required this.onPrimaryContainer,
    required this.secondary,
    required this.onSecondary,
    required this.secondaryContainer,
    required this.onSecondaryContainer,
    required this.tertiary,
    required this.onTertiary,
    required this.tertiaryContainer,
    required this.onTertiaryContainer,
    required this.error,
    required this.onError,
    required this.errorContainer,
    required this.onErrorContainer,
    required this.surface,
    required this.onSurface,
    required this.surfaceDim,
    required this.surfaceBright,
    required this.surfaceContainerLowest,
    required this.surfaceContainerLow,
    required this.surfaceContainer,
    required this.surfaceContainerHigh,
    required this.surfaceContainerHighest,
    required this.onSurfaceVariant,
    required this.outline,
    required this.outlineVariant,
    required this.shadow,
    required this.scrim,
    required this.inverseSurface,
    required this.onInverseSurface,
    required this.inversePrimary,
    required this.surfaceTint,
    required this.shimmer,
    required this.approval,
    required this.hoverOverlay,
    required this.pressedOverlay,
  });

  // Locnet Messenger light theme — mirrors --bg-primary / accent / text tokens
  // from the HTML prototype (Locnet Messenger.html).
  const AppColorScheme.light()
    : primary = const Color(0xFF4A90E2),         // --accent
      onPrimary = const Color(0xFFFFFFFF),
      primaryContainer = const Color(0x154A90E2), // --accent-muted light
      onPrimaryContainer = const Color(0xFF0F1117),
      secondary = const Color(0xFFF4F5F7),        // --bg-secondary
      onSecondary = const Color(0xFF0F1117),
      secondaryContainer = const Color(0xFFE8EAF0), // --bg-tertiary
      onSecondaryContainer = const Color(0xFF0F1117),
      tertiary = const Color(0xFF4A90E2),
      onTertiary = const Color(0xFFFFFFFF),
      tertiaryContainer = const Color(0x154A90E2),
      onTertiaryContainer = const Color(0xFF0F1117),
      error = const Color(0xFFE05050),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0x1AE05050),
      onErrorContainer = const Color(0xFF7A0000),
      surface = const Color(0xFFFFFFFF),           // --bg-primary
      onSurface = const Color(0xFF0F1117),          // --text-primary
      surfaceDim = const Color(0xFFE8EAF0),         // --bg-tertiary
      surfaceBright = const Color(0xFFFFFFFF),
      surfaceContainerLowest = const Color(0xFFFFFFFF),
      surfaceContainerLow = const Color(0xFFF4F5F7),  // --bg-secondary
      surfaceContainer = const Color(0xFFE8EAF0),     // --bg-tertiary
      surfaceContainerHigh = const Color(0xFFDDE1EA), // --border
      surfaceContainerHighest = const Color(0xFFD0D4DE),
      onSurfaceVariant = const Color(0xFF5A6070),     // --text-secondary
      outline = const Color(0xFFDDE1EA),              // --border
      outlineVariant = const Color(0xFFE8EAF0),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFF0F1117),
      onInverseSurface = const Color(0xFFE8ECF4),
      inversePrimary = const Color(0xFF4A90E2),
      surfaceTint = const Color(0xFF4A90E2),
      shimmer = const Color(0xFFE8EAF0),
      approval = const Color(0xFF4CAF79),
      hoverOverlay = const Color(0x0A000000),
      pressedOverlay = const Color(0x14000000);

  // Locnet Messenger dark theme — mirrors CSS variables from HTML prototype.
  const AppColorScheme.dark()
    : primary = const Color(0xFF4A90E2),           // --accent
      onPrimary = const Color(0xFFFFFFFF),
      primaryContainer = const Color(0x224A90E2),   // --accent-muted dark
      onPrimaryContainer = const Color(0xFFE8ECF4),
      secondary = const Color(0xFF181B24),           // --bg-secondary
      onSecondary = const Color(0xFFE8ECF4),
      secondaryContainer = const Color(0xFF1F2330),  // --bg-tertiary
      onSecondaryContainer = const Color(0xFFE8ECF4),
      tertiary = const Color(0xFF4A90E2),
      onTertiary = const Color(0xFFFFFFFF),
      tertiaryContainer = const Color(0x224A90E2),
      onTertiaryContainer = const Color(0xFFE8ECF4),
      error = const Color(0xFFE05050),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0x33E05050),
      onErrorContainer = const Color(0xFFFFCDD2),
      surface = const Color(0xFF0F1117),             // --bg-primary
      onSurface = const Color(0xFFE8ECF4),           // --text-primary
      surfaceDim = const Color(0xFF0A0C12),
      surfaceBright = const Color(0xFF252A38),        // --border
      surfaceContainerLowest = const Color(0xFF0A0C12),
      surfaceContainerLow = const Color(0xFF181B24),  // --bg-secondary
      surfaceContainer = const Color(0xFF1F2330),     // --bg-tertiary
      surfaceContainerHigh = const Color(0xFF252A38), // --border
      surfaceContainerHighest = const Color(0xFF2D3245),
      onSurfaceVariant = const Color(0xFF8B93A8),     // --text-secondary
      outline = const Color(0xFF252A38),              // --border
      outlineVariant = const Color(0xFF1F2330),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFFE8ECF4),
      onInverseSurface = const Color(0xFF0F1117),
      inversePrimary = const Color(0xFF4A90E2),
      surfaceTint = const Color(0xFF4A90E2),
      shimmer = const Color(0xFF1F2330),
      approval = const Color(0xFF4CAF79),
      hoverOverlay = const Color(0x14FFFFFF),
      pressedOverlay = const Color(0x21FFFFFF);

  // --- Light Blue (accent 1) — Locnet surfaces + blue accent ---
  const AppColorScheme.lightBlue()
    : primary = const Color(0xFF1976D2),
      onPrimary = const Color(0xFFFFFFFF),
      primaryContainer = const Color(0x201976D2),
      onPrimaryContainer = const Color(0xFF0F1117),
      secondary = const Color(0xFFF4F5F7),
      onSecondary = const Color(0xFF0F1117),
      secondaryContainer = const Color(0xFFE8EAF0),
      onSecondaryContainer = const Color(0xFF0F1117),
      tertiary = const Color(0xFF1976D2),
      onTertiary = const Color(0xFFFFFFFF),
      tertiaryContainer = const Color(0x201976D2),
      onTertiaryContainer = const Color(0xFF0F1117),
      error = const Color(0xFFE05050),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0x1AE05050),
      onErrorContainer = const Color(0xFF7A0000),
      surface = const Color(0xFFFFFFFF),
      onSurface = const Color(0xFF0F1117),
      surfaceDim = const Color(0xFFE8EAF0),
      surfaceBright = const Color(0xFFFFFFFF),
      surfaceContainerLowest = const Color(0xFFFFFFFF),
      surfaceContainerLow = const Color(0xFFF4F5F7),
      surfaceContainer = const Color(0xFFE8EAF0),
      surfaceContainerHigh = const Color(0xFFDDE1EA),
      surfaceContainerHighest = const Color(0xFFD0D4DE),
      onSurfaceVariant = const Color(0xFF5A6070),
      outline = const Color(0xFFDDE1EA),
      outlineVariant = const Color(0xFFE8EAF0),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFF0F1117),
      onInverseSurface = const Color(0xFFE8ECF4),
      inversePrimary = const Color(0xFF1976D2),
      surfaceTint = const Color(0xFF1976D2),
      shimmer = const Color(0xFFE8EAF0),
      approval = const Color(0xFF4CAF79),
      hoverOverlay = const Color(0x0A000000),
      pressedOverlay = const Color(0x14000000);

  // --- Light Green (accent 2) — Locnet surfaces + green accent ---
  const AppColorScheme.lightGreen()
    : primary = const Color(0xFF2E7D32),
      onPrimary = const Color(0xFFFFFFFF),
      primaryContainer = const Color(0x202E7D32),
      onPrimaryContainer = const Color(0xFF0F1117),
      secondary = const Color(0xFFF4F5F7),
      onSecondary = const Color(0xFF0F1117),
      secondaryContainer = const Color(0xFFE8EAF0),
      onSecondaryContainer = const Color(0xFF0F1117),
      tertiary = const Color(0xFF2E7D32),
      onTertiary = const Color(0xFFFFFFFF),
      tertiaryContainer = const Color(0x202E7D32),
      onTertiaryContainer = const Color(0xFF0F1117),
      error = const Color(0xFFE05050),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0x1AE05050),
      onErrorContainer = const Color(0xFF7A0000),
      surface = const Color(0xFFFFFFFF),
      onSurface = const Color(0xFF0F1117),
      surfaceDim = const Color(0xFFE8EAF0),
      surfaceBright = const Color(0xFFFFFFFF),
      surfaceContainerLowest = const Color(0xFFFFFFFF),
      surfaceContainerLow = const Color(0xFFF4F5F7),
      surfaceContainer = const Color(0xFFE8EAF0),
      surfaceContainerHigh = const Color(0xFFDDE1EA),
      surfaceContainerHighest = const Color(0xFFD0D4DE),
      onSurfaceVariant = const Color(0xFF5A6070),
      outline = const Color(0xFFDDE1EA),
      outlineVariant = const Color(0xFFE8EAF0),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFF0F1117),
      onInverseSurface = const Color(0xFFE8ECF4),
      inversePrimary = const Color(0xFF2E7D32),
      surfaceTint = const Color(0xFF2E7D32),
      shimmer = const Color(0xFFE8EAF0),
      approval = const Color(0xFF4CAF79),
      hoverOverlay = const Color(0x0A000000),
      pressedOverlay = const Color(0x14000000);

  // --- Light Purple (accent 3) — Locnet surfaces + purple accent ---
  const AppColorScheme.lightPurple()
    : primary = const Color(0xFF7B1FA2),
      onPrimary = const Color(0xFFFFFFFF),
      primaryContainer = const Color(0x207B1FA2),
      onPrimaryContainer = const Color(0xFF0F1117),
      secondary = const Color(0xFFF4F5F7),
      onSecondary = const Color(0xFF0F1117),
      secondaryContainer = const Color(0xFFE8EAF0),
      onSecondaryContainer = const Color(0xFF0F1117),
      tertiary = const Color(0xFF7B1FA2),
      onTertiary = const Color(0xFFFFFFFF),
      tertiaryContainer = const Color(0x207B1FA2),
      onTertiaryContainer = const Color(0xFF0F1117),
      error = const Color(0xFFE05050),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0x1AE05050),
      onErrorContainer = const Color(0xFF7A0000),
      surface = const Color(0xFFFFFFFF),
      onSurface = const Color(0xFF0F1117),
      surfaceDim = const Color(0xFFE8EAF0),
      surfaceBright = const Color(0xFFFFFFFF),
      surfaceContainerLowest = const Color(0xFFFFFFFF),
      surfaceContainerLow = const Color(0xFFF4F5F7),
      surfaceContainer = const Color(0xFFE8EAF0),
      surfaceContainerHigh = const Color(0xFFDDE1EA),
      surfaceContainerHighest = const Color(0xFFD0D4DE),
      onSurfaceVariant = const Color(0xFF5A6070),
      outline = const Color(0xFFDDE1EA),
      outlineVariant = const Color(0xFFE8EAF0),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFF0F1117),
      onInverseSurface = const Color(0xFFE8ECF4),
      inversePrimary = const Color(0xFF7B1FA2),
      surfaceTint = const Color(0xFF7B1FA2),
      shimmer = const Color(0xFFE8EAF0),
      approval = const Color(0xFF4CAF79),
      hoverOverlay = const Color(0x0A000000),
      pressedOverlay = const Color(0x14000000);

  // --- Dark Blue (accent 1) — Locnet dark surfaces + blue accent ---
  const AppColorScheme.darkBlue()
    : primary = const Color(0xFF5BA8F5),
      onPrimary = const Color(0xFFFFFFFF),
      primaryContainer = const Color(0x225BA8F5),
      onPrimaryContainer = const Color(0xFFE8ECF4),
      secondary = const Color(0xFF181B24),
      onSecondary = const Color(0xFFE8ECF4),
      secondaryContainer = const Color(0xFF1F2330),
      onSecondaryContainer = const Color(0xFFE8ECF4),
      tertiary = const Color(0xFF5BA8F5),
      onTertiary = const Color(0xFFFFFFFF),
      tertiaryContainer = const Color(0x225BA8F5),
      onTertiaryContainer = const Color(0xFFE8ECF4),
      error = const Color(0xFFE05050),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0x33E05050),
      onErrorContainer = const Color(0xFFFFCDD2),
      surface = const Color(0xFF0F1117),
      onSurface = const Color(0xFFE8ECF4),
      surfaceDim = const Color(0xFF0A0C12),
      surfaceBright = const Color(0xFF252A38),
      surfaceContainerLowest = const Color(0xFF0A0C12),
      surfaceContainerLow = const Color(0xFF181B24),
      surfaceContainer = const Color(0xFF1F2330),
      surfaceContainerHigh = const Color(0xFF252A38),
      surfaceContainerHighest = const Color(0xFF2D3245),
      onSurfaceVariant = const Color(0xFF8B93A8),
      outline = const Color(0xFF252A38),
      outlineVariant = const Color(0xFF1F2330),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFFE8ECF4),
      onInverseSurface = const Color(0xFF0F1117),
      inversePrimary = const Color(0xFF5BA8F5),
      surfaceTint = const Color(0xFF5BA8F5),
      shimmer = const Color(0xFF1F2330),
      approval = const Color(0xFF4CAF79),
      hoverOverlay = const Color(0x14FFFFFF),
      pressedOverlay = const Color(0x21FFFFFF);

  // --- Dark Green (accent 2) — Locnet dark surfaces + green accent ---
  const AppColorScheme.darkGreen()
    : primary = const Color(0xFF4CAF79),
      onPrimary = const Color(0xFFFFFFFF),
      primaryContainer = const Color(0x224CAF79),
      onPrimaryContainer = const Color(0xFFE8ECF4),
      secondary = const Color(0xFF181B24),
      onSecondary = const Color(0xFFE8ECF4),
      secondaryContainer = const Color(0xFF1F2330),
      onSecondaryContainer = const Color(0xFFE8ECF4),
      tertiary = const Color(0xFF4CAF79),
      onTertiary = const Color(0xFFFFFFFF),
      tertiaryContainer = const Color(0x224CAF79),
      onTertiaryContainer = const Color(0xFFE8ECF4),
      error = const Color(0xFFE05050),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0x33E05050),
      onErrorContainer = const Color(0xFFFFCDD2),
      surface = const Color(0xFF0F1117),
      onSurface = const Color(0xFFE8ECF4),
      surfaceDim = const Color(0xFF0A0C12),
      surfaceBright = const Color(0xFF252A38),
      surfaceContainerLowest = const Color(0xFF0A0C12),
      surfaceContainerLow = const Color(0xFF181B24),
      surfaceContainer = const Color(0xFF1F2330),
      surfaceContainerHigh = const Color(0xFF252A38),
      surfaceContainerHighest = const Color(0xFF2D3245),
      onSurfaceVariant = const Color(0xFF8B93A8),
      outline = const Color(0xFF252A38),
      outlineVariant = const Color(0xFF1F2330),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFFE8ECF4),
      onInverseSurface = const Color(0xFF0F1117),
      inversePrimary = const Color(0xFF4CAF79),
      surfaceTint = const Color(0xFF4CAF79),
      shimmer = const Color(0xFF1F2330),
      approval = const Color(0xFF4CAF79),
      hoverOverlay = const Color(0x14FFFFFF),
      pressedOverlay = const Color(0x21FFFFFF);

  // --- Dark Purple (accent 3) — Locnet dark surfaces + purple accent ---
  const AppColorScheme.darkPurple()
    : primary = const Color(0xFFB06AE0),
      onPrimary = const Color(0xFFFFFFFF),
      primaryContainer = const Color(0x22B06AE0),
      onPrimaryContainer = const Color(0xFFE8ECF4),
      secondary = const Color(0xFF181B24),
      onSecondary = const Color(0xFFE8ECF4),
      secondaryContainer = const Color(0xFF1F2330),
      onSecondaryContainer = const Color(0xFFE8ECF4),
      tertiary = const Color(0xFFB06AE0),
      onTertiary = const Color(0xFFFFFFFF),
      tertiaryContainer = const Color(0x22B06AE0),
      onTertiaryContainer = const Color(0xFFE8ECF4),
      error = const Color(0xFFE05050),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0x33E05050),
      onErrorContainer = const Color(0xFFFFCDD2),
      surface = const Color(0xFF0F1117),
      onSurface = const Color(0xFFE8ECF4),
      surfaceDim = const Color(0xFF0A0C12),
      surfaceBright = const Color(0xFF252A38),
      surfaceContainerLowest = const Color(0xFF0A0C12),
      surfaceContainerLow = const Color(0xFF181B24),
      surfaceContainer = const Color(0xFF1F2330),
      surfaceContainerHigh = const Color(0xFF252A38),
      surfaceContainerHighest = const Color(0xFF2D3245),
      onSurfaceVariant = const Color(0xFF8B93A8),
      outline = const Color(0xFF252A38),
      outlineVariant = const Color(0xFF1F2330),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFFE8ECF4),
      onInverseSurface = const Color(0xFF0F1117),
      inversePrimary = const Color(0xFFB06AE0),
      surfaceTint = const Color(0xFFB06AE0),
      shimmer = const Color(0xFF1F2330),
      approval = const Color(0xFF4CAF79),
      hoverOverlay = const Color(0x14FFFFFF),
      pressedOverlay = const Color(0x21FFFFFF);

  // --- Light Orange (accent 4) ---
  const AppColorScheme.lightOrange()
    : primary = const Color(0xFFEF6C00),
      onPrimary = const Color(0xFFFFFFFF),
      primaryContainer = const Color(0x20EF6C00),
      onPrimaryContainer = const Color(0xFF0F1117),
      secondary = const Color(0xFFF4F5F7),
      onSecondary = const Color(0xFF0F1117),
      secondaryContainer = const Color(0xFFE8EAF0),
      onSecondaryContainer = const Color(0xFF0F1117),
      tertiary = const Color(0xFFEF6C00),
      onTertiary = const Color(0xFFFFFFFF),
      tertiaryContainer = const Color(0x20EF6C00),
      onTertiaryContainer = const Color(0xFF0F1117),
      error = const Color(0xFFE05050),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0x1AE05050),
      onErrorContainer = const Color(0xFF7A0000),
      surface = const Color(0xFFFFFFFF),
      onSurface = const Color(0xFF0F1117),
      surfaceDim = const Color(0xFFE8EAF0),
      surfaceBright = const Color(0xFFFFFFFF),
      surfaceContainerLowest = const Color(0xFFFFFFFF),
      surfaceContainerLow = const Color(0xFFF4F5F7),
      surfaceContainer = const Color(0xFFE8EAF0),
      surfaceContainerHigh = const Color(0xFFDDE1EA),
      surfaceContainerHighest = const Color(0xFFD0D4DE),
      onSurfaceVariant = const Color(0xFF5A6070),
      outline = const Color(0xFFDDE1EA),
      outlineVariant = const Color(0xFFE8EAF0),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFF0F1117),
      onInverseSurface = const Color(0xFFE8ECF4),
      inversePrimary = const Color(0xFFEF6C00),
      surfaceTint = const Color(0xFFEF6C00),
      shimmer = const Color(0xFFE8EAF0),
      approval = const Color(0xFF4CAF79),
      hoverOverlay = const Color(0x0A000000),
      pressedOverlay = const Color(0x14000000);

  // --- Light Teal (accent 5) ---
  const AppColorScheme.lightTeal()
    : primary = const Color(0xFF00796B),
      onPrimary = const Color(0xFFFFFFFF),
      primaryContainer = const Color(0x2000796B),
      onPrimaryContainer = const Color(0xFF0F1117),
      secondary = const Color(0xFFF4F5F7),
      onSecondary = const Color(0xFF0F1117),
      secondaryContainer = const Color(0xFFE8EAF0),
      onSecondaryContainer = const Color(0xFF0F1117),
      tertiary = const Color(0xFF00796B),
      onTertiary = const Color(0xFFFFFFFF),
      tertiaryContainer = const Color(0x2000796B),
      onTertiaryContainer = const Color(0xFF0F1117),
      error = const Color(0xFFE05050),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0x1AE05050),
      onErrorContainer = const Color(0xFF7A0000),
      surface = const Color(0xFFFFFFFF),
      onSurface = const Color(0xFF0F1117),
      surfaceDim = const Color(0xFFE8EAF0),
      surfaceBright = const Color(0xFFFFFFFF),
      surfaceContainerLowest = const Color(0xFFFFFFFF),
      surfaceContainerLow = const Color(0xFFF4F5F7),
      surfaceContainer = const Color(0xFFE8EAF0),
      surfaceContainerHigh = const Color(0xFFDDE1EA),
      surfaceContainerHighest = const Color(0xFFD0D4DE),
      onSurfaceVariant = const Color(0xFF5A6070),
      outline = const Color(0xFFDDE1EA),
      outlineVariant = const Color(0xFFE8EAF0),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFF0F1117),
      onInverseSurface = const Color(0xFFE8ECF4),
      inversePrimary = const Color(0xFF00796B),
      surfaceTint = const Color(0xFF00796B),
      shimmer = const Color(0xFFE8EAF0),
      approval = const Color(0xFF4CAF79),
      hoverOverlay = const Color(0x0A000000),
      pressedOverlay = const Color(0x14000000);

  // --- Light Amber (accent 6) ---
  const AppColorScheme.lightAmber()
    : primary = const Color(0xFFF57C00),
      onPrimary = const Color(0xFFFFFFFF),
      primaryContainer = const Color(0x20F57C00),
      onPrimaryContainer = const Color(0xFF0F1117),
      secondary = const Color(0xFFF4F5F7),
      onSecondary = const Color(0xFF0F1117),
      secondaryContainer = const Color(0xFFE8EAF0),
      onSecondaryContainer = const Color(0xFF0F1117),
      tertiary = const Color(0xFFF57C00),
      onTertiary = const Color(0xFFFFFFFF),
      tertiaryContainer = const Color(0x20F57C00),
      onTertiaryContainer = const Color(0xFF0F1117),
      error = const Color(0xFFE05050),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0x1AE05050),
      onErrorContainer = const Color(0xFF7A0000),
      surface = const Color(0xFFFFFFFF),
      onSurface = const Color(0xFF0F1117),
      surfaceDim = const Color(0xFFE8EAF0),
      surfaceBright = const Color(0xFFFFFFFF),
      surfaceContainerLowest = const Color(0xFFFFFFFF),
      surfaceContainerLow = const Color(0xFFF4F5F7),
      surfaceContainer = const Color(0xFFE8EAF0),
      surfaceContainerHigh = const Color(0xFFDDE1EA),
      surfaceContainerHighest = const Color(0xFFD0D4DE),
      onSurfaceVariant = const Color(0xFF5A6070),
      outline = const Color(0xFFDDE1EA),
      outlineVariant = const Color(0xFFE8EAF0),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFF0F1117),
      onInverseSurface = const Color(0xFFE8ECF4),
      inversePrimary = const Color(0xFFF57C00),
      surfaceTint = const Color(0xFFF57C00),
      shimmer = const Color(0xFFE8EAF0),
      approval = const Color(0xFF4CAF79),
      hoverOverlay = const Color(0x0A000000),
      pressedOverlay = const Color(0x14000000);

  // --- Light Pink (accent 7) ---
  const AppColorScheme.lightPink()
    : primary = const Color(0xFFC2185B),
      onPrimary = const Color(0xFFFFFFFF),
      primaryContainer = const Color(0x20C2185B),
      onPrimaryContainer = const Color(0xFF0F1117),
      secondary = const Color(0xFFF4F5F7),
      onSecondary = const Color(0xFF0F1117),
      secondaryContainer = const Color(0xFFE8EAF0),
      onSecondaryContainer = const Color(0xFF0F1117),
      tertiary = const Color(0xFFC2185B),
      onTertiary = const Color(0xFFFFFFFF),
      tertiaryContainer = const Color(0x20C2185B),
      onTertiaryContainer = const Color(0xFF0F1117),
      error = const Color(0xFFE05050),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0x1AE05050),
      onErrorContainer = const Color(0xFF7A0000),
      surface = const Color(0xFFFFFFFF),
      onSurface = const Color(0xFF0F1117),
      surfaceDim = const Color(0xFFE8EAF0),
      surfaceBright = const Color(0xFFFFFFFF),
      surfaceContainerLowest = const Color(0xFFFFFFFF),
      surfaceContainerLow = const Color(0xFFF4F5F7),
      surfaceContainer = const Color(0xFFE8EAF0),
      surfaceContainerHigh = const Color(0xFFDDE1EA),
      surfaceContainerHighest = const Color(0xFFD0D4DE),
      onSurfaceVariant = const Color(0xFF5A6070),
      outline = const Color(0xFFDDE1EA),
      outlineVariant = const Color(0xFFE8EAF0),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFF0F1117),
      onInverseSurface = const Color(0xFFE8ECF4),
      inversePrimary = const Color(0xFFC2185B),
      surfaceTint = const Color(0xFFC2185B),
      shimmer = const Color(0xFFE8EAF0),
      approval = const Color(0xFF4CAF79),
      hoverOverlay = const Color(0x0A000000),
      pressedOverlay = const Color(0x14000000);

  // --- Light Indigo (accent 8) ---
  const AppColorScheme.lightIndigo()
    : primary = const Color(0xFF3949AB),
      onPrimary = const Color(0xFFFFFFFF),
      primaryContainer = const Color(0x203949AB),
      onPrimaryContainer = const Color(0xFF0F1117),
      secondary = const Color(0xFFF4F5F7),
      onSecondary = const Color(0xFF0F1117),
      secondaryContainer = const Color(0xFFE8EAF0),
      onSecondaryContainer = const Color(0xFF0F1117),
      tertiary = const Color(0xFF3949AB),
      onTertiary = const Color(0xFFFFFFFF),
      tertiaryContainer = const Color(0x203949AB),
      onTertiaryContainer = const Color(0xFF0F1117),
      error = const Color(0xFFE05050),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0x1AE05050),
      onErrorContainer = const Color(0xFF7A0000),
      surface = const Color(0xFFFFFFFF),
      onSurface = const Color(0xFF0F1117),
      surfaceDim = const Color(0xFFE8EAF0),
      surfaceBright = const Color(0xFFFFFFFF),
      surfaceContainerLowest = const Color(0xFFFFFFFF),
      surfaceContainerLow = const Color(0xFFF4F5F7),
      surfaceContainer = const Color(0xFFE8EAF0),
      surfaceContainerHigh = const Color(0xFFDDE1EA),
      surfaceContainerHighest = const Color(0xFFD0D4DE),
      onSurfaceVariant = const Color(0xFF5A6070),
      outline = const Color(0xFFDDE1EA),
      outlineVariant = const Color(0xFFE8EAF0),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFF0F1117),
      onInverseSurface = const Color(0xFFE8ECF4),
      inversePrimary = const Color(0xFF3949AB),
      surfaceTint = const Color(0xFF3949AB),
      shimmer = const Color(0xFFE8EAF0),
      approval = const Color(0xFF4CAF79),
      hoverOverlay = const Color(0x0A000000),
      pressedOverlay = const Color(0x14000000);

  // --- Light Red (accent 9) ---
  const AppColorScheme.lightRed()
    : primary = const Color(0xFFC62828),
      onPrimary = const Color(0xFFFFFFFF),
      primaryContainer = const Color(0x20C62828),
      onPrimaryContainer = const Color(0xFF0F1117),
      secondary = const Color(0xFFF4F5F7),
      onSecondary = const Color(0xFF0F1117),
      secondaryContainer = const Color(0xFFE8EAF0),
      onSecondaryContainer = const Color(0xFF0F1117),
      tertiary = const Color(0xFFC62828),
      onTertiary = const Color(0xFFFFFFFF),
      tertiaryContainer = const Color(0x20C62828),
      onTertiaryContainer = const Color(0xFF0F1117),
      error = const Color(0xFFE05050),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0x1AE05050),
      onErrorContainer = const Color(0xFF7A0000),
      surface = const Color(0xFFFFFFFF),
      onSurface = const Color(0xFF0F1117),
      surfaceDim = const Color(0xFFE8EAF0),
      surfaceBright = const Color(0xFFFFFFFF),
      surfaceContainerLowest = const Color(0xFFFFFFFF),
      surfaceContainerLow = const Color(0xFFF4F5F7),
      surfaceContainer = const Color(0xFFE8EAF0),
      surfaceContainerHigh = const Color(0xFFDDE1EA),
      surfaceContainerHighest = const Color(0xFFD0D4DE),
      onSurfaceVariant = const Color(0xFF5A6070),
      outline = const Color(0xFFDDE1EA),
      outlineVariant = const Color(0xFFE8EAF0),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFF0F1117),
      onInverseSurface = const Color(0xFFE8ECF4),
      inversePrimary = const Color(0xFFC62828),
      surfaceTint = const Color(0xFFC62828),
      shimmer = const Color(0xFFE8EAF0),
      approval = const Color(0xFF4CAF79),
      hoverOverlay = const Color(0x0A000000),
      pressedOverlay = const Color(0x14000000);

  // --- Dark Orange (accent 4) ---
  const AppColorScheme.darkOrange()
    : primary = const Color(0xFFFFB74D),
      onPrimary = const Color(0xFF2D1600),
      primaryContainer = const Color(0x22FFB74D),
      onPrimaryContainer = const Color(0xFFE8ECF4),
      secondary = const Color(0xFF181B24),
      onSecondary = const Color(0xFFE8ECF4),
      secondaryContainer = const Color(0xFF1F2330),
      onSecondaryContainer = const Color(0xFFE8ECF4),
      tertiary = const Color(0xFFFFB74D),
      onTertiary = const Color(0xFF2D1600),
      tertiaryContainer = const Color(0x22FFB74D),
      onTertiaryContainer = const Color(0xFFE8ECF4),
      error = const Color(0xFFE05050),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0x33E05050),
      onErrorContainer = const Color(0xFFFFCDD2),
      surface = const Color(0xFF0F1117),
      onSurface = const Color(0xFFE8ECF4),
      surfaceDim = const Color(0xFF0A0C12),
      surfaceBright = const Color(0xFF252A38),
      surfaceContainerLowest = const Color(0xFF0A0C12),
      surfaceContainerLow = const Color(0xFF181B24),
      surfaceContainer = const Color(0xFF1F2330),
      surfaceContainerHigh = const Color(0xFF252A38),
      surfaceContainerHighest = const Color(0xFF2D3245),
      onSurfaceVariant = const Color(0xFF8B93A8),
      outline = const Color(0xFF252A38),
      outlineVariant = const Color(0xFF1F2330),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFFE8ECF4),
      onInverseSurface = const Color(0xFF0F1117),
      inversePrimary = const Color(0xFFFFB74D),
      surfaceTint = const Color(0xFFFFB74D),
      shimmer = const Color(0xFF1F2330),
      approval = const Color(0xFF4CAF79),
      hoverOverlay = const Color(0x14FFFFFF),
      pressedOverlay = const Color(0x21FFFFFF);

  // --- Dark Teal (accent 5) ---
  const AppColorScheme.darkTeal()
    : primary = const Color(0xFF4DB6AC),
      onPrimary = const Color(0xFF002722),
      primaryContainer = const Color(0x224DB6AC),
      onPrimaryContainer = const Color(0xFFE8ECF4),
      secondary = const Color(0xFF181B24),
      onSecondary = const Color(0xFFE8ECF4),
      secondaryContainer = const Color(0xFF1F2330),
      onSecondaryContainer = const Color(0xFFE8ECF4),
      tertiary = const Color(0xFF4DB6AC),
      onTertiary = const Color(0xFF002722),
      tertiaryContainer = const Color(0x224DB6AC),
      onTertiaryContainer = const Color(0xFFE8ECF4),
      error = const Color(0xFFE05050),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0x33E05050),
      onErrorContainer = const Color(0xFFFFCDD2),
      surface = const Color(0xFF0F1117),
      onSurface = const Color(0xFFE8ECF4),
      surfaceDim = const Color(0xFF0A0C12),
      surfaceBright = const Color(0xFF252A38),
      surfaceContainerLowest = const Color(0xFF0A0C12),
      surfaceContainerLow = const Color(0xFF181B24),
      surfaceContainer = const Color(0xFF1F2330),
      surfaceContainerHigh = const Color(0xFF252A38),
      surfaceContainerHighest = const Color(0xFF2D3245),
      onSurfaceVariant = const Color(0xFF8B93A8),
      outline = const Color(0xFF252A38),
      outlineVariant = const Color(0xFF1F2330),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFFE8ECF4),
      onInverseSurface = const Color(0xFF0F1117),
      inversePrimary = const Color(0xFF4DB6AC),
      surfaceTint = const Color(0xFF4DB6AC),
      shimmer = const Color(0xFF1F2330),
      approval = const Color(0xFF4CAF79),
      hoverOverlay = const Color(0x14FFFFFF),
      pressedOverlay = const Color(0x21FFFFFF);

  // --- Dark Amber (accent 6) ---
  const AppColorScheme.darkAmber()
    : primary = const Color(0xFFFFCA28),
      onPrimary = const Color(0xFF2D2100),
      primaryContainer = const Color(0x22FFCA28),
      onPrimaryContainer = const Color(0xFFE8ECF4),
      secondary = const Color(0xFF181B24),
      onSecondary = const Color(0xFFE8ECF4),
      secondaryContainer = const Color(0xFF1F2330),
      onSecondaryContainer = const Color(0xFFE8ECF4),
      tertiary = const Color(0xFFFFCA28),
      onTertiary = const Color(0xFF2D2100),
      tertiaryContainer = const Color(0x22FFCA28),
      onTertiaryContainer = const Color(0xFFE8ECF4),
      error = const Color(0xFFE05050),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0x33E05050),
      onErrorContainer = const Color(0xFFFFCDD2),
      surface = const Color(0xFF0F1117),
      onSurface = const Color(0xFFE8ECF4),
      surfaceDim = const Color(0xFF0A0C12),
      surfaceBright = const Color(0xFF252A38),
      surfaceContainerLowest = const Color(0xFF0A0C12),
      surfaceContainerLow = const Color(0xFF181B24),
      surfaceContainer = const Color(0xFF1F2330),
      surfaceContainerHigh = const Color(0xFF252A38),
      surfaceContainerHighest = const Color(0xFF2D3245),
      onSurfaceVariant = const Color(0xFF8B93A8),
      outline = const Color(0xFF252A38),
      outlineVariant = const Color(0xFF1F2330),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFFE8ECF4),
      onInverseSurface = const Color(0xFF0F1117),
      inversePrimary = const Color(0xFFFFCA28),
      surfaceTint = const Color(0xFFFFCA28),
      shimmer = const Color(0xFF1F2330),
      approval = const Color(0xFF4CAF79),
      hoverOverlay = const Color(0x14FFFFFF),
      pressedOverlay = const Color(0x21FFFFFF);

  // --- Dark Pink (accent 7) ---
  const AppColorScheme.darkPink()
    : primary = const Color(0xFFF48FB1),
      onPrimary = const Color(0xFF3D0D22),
      primaryContainer = const Color(0x22F48FB1),
      onPrimaryContainer = const Color(0xFFE8ECF4),
      secondary = const Color(0xFF181B24),
      onSecondary = const Color(0xFFE8ECF4),
      secondaryContainer = const Color(0xFF1F2330),
      onSecondaryContainer = const Color(0xFFE8ECF4),
      tertiary = const Color(0xFFF48FB1),
      onTertiary = const Color(0xFF3D0D22),
      tertiaryContainer = const Color(0x22F48FB1),
      onTertiaryContainer = const Color(0xFFE8ECF4),
      error = const Color(0xFFE05050),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0x33E05050),
      onErrorContainer = const Color(0xFFFFCDD2),
      surface = const Color(0xFF0F1117),
      onSurface = const Color(0xFFE8ECF4),
      surfaceDim = const Color(0xFF0A0C12),
      surfaceBright = const Color(0xFF252A38),
      surfaceContainerLowest = const Color(0xFF0A0C12),
      surfaceContainerLow = const Color(0xFF181B24),
      surfaceContainer = const Color(0xFF1F2330),
      surfaceContainerHigh = const Color(0xFF252A38),
      surfaceContainerHighest = const Color(0xFF2D3245),
      onSurfaceVariant = const Color(0xFF8B93A8),
      outline = const Color(0xFF252A38),
      outlineVariant = const Color(0xFF1F2330),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFFE8ECF4),
      onInverseSurface = const Color(0xFF0F1117),
      inversePrimary = const Color(0xFFF48FB1),
      surfaceTint = const Color(0xFFF48FB1),
      shimmer = const Color(0xFF1F2330),
      approval = const Color(0xFF4CAF79),
      hoverOverlay = const Color(0x14FFFFFF),
      pressedOverlay = const Color(0x21FFFFFF);

  // --- Dark Indigo (accent 8) ---
  const AppColorScheme.darkIndigo()
    : primary = const Color(0xFF9FA8DA),
      onPrimary = const Color(0xFF1A1F4A),
      primaryContainer = const Color(0x229FA8DA),
      onPrimaryContainer = const Color(0xFFE8ECF4),
      secondary = const Color(0xFF181B24),
      onSecondary = const Color(0xFFE8ECF4),
      secondaryContainer = const Color(0xFF1F2330),
      onSecondaryContainer = const Color(0xFFE8ECF4),
      tertiary = const Color(0xFF9FA8DA),
      onTertiary = const Color(0xFF1A1F4A),
      tertiaryContainer = const Color(0x229FA8DA),
      onTertiaryContainer = const Color(0xFFE8ECF4),
      error = const Color(0xFFE05050),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0x33E05050),
      onErrorContainer = const Color(0xFFFFCDD2),
      surface = const Color(0xFF0F1117),
      onSurface = const Color(0xFFE8ECF4),
      surfaceDim = const Color(0xFF0A0C12),
      surfaceBright = const Color(0xFF252A38),
      surfaceContainerLowest = const Color(0xFF0A0C12),
      surfaceContainerLow = const Color(0xFF181B24),
      surfaceContainer = const Color(0xFF1F2330),
      surfaceContainerHigh = const Color(0xFF252A38),
      surfaceContainerHighest = const Color(0xFF2D3245),
      onSurfaceVariant = const Color(0xFF8B93A8),
      outline = const Color(0xFF252A38),
      outlineVariant = const Color(0xFF1F2330),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFFE8ECF4),
      onInverseSurface = const Color(0xFF0F1117),
      inversePrimary = const Color(0xFF9FA8DA),
      surfaceTint = const Color(0xFF9FA8DA),
      shimmer = const Color(0xFF1F2330),
      approval = const Color(0xFF4CAF79),
      hoverOverlay = const Color(0x14FFFFFF),
      pressedOverlay = const Color(0x21FFFFFF);

  // --- Dark Red (accent 9) ---
  const AppColorScheme.darkRed()
    : primary = const Color(0xFFEF5350),
      onPrimary = const Color(0xFF3D0A0A),
      primaryContainer = const Color(0x22EF5350),
      onPrimaryContainer = const Color(0xFFE8ECF4),
      secondary = const Color(0xFF181B24),
      onSecondary = const Color(0xFFE8ECF4),
      secondaryContainer = const Color(0xFF1F2330),
      onSecondaryContainer = const Color(0xFFE8ECF4),
      tertiary = const Color(0xFFEF5350),
      onTertiary = const Color(0xFF3D0A0A),
      tertiaryContainer = const Color(0x22EF5350),
      onTertiaryContainer = const Color(0xFFE8ECF4),
      error = const Color(0xFFE05050),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0x33E05050),
      onErrorContainer = const Color(0xFFFFCDD2),
      surface = const Color(0xFF0F1117),
      onSurface = const Color(0xFFE8ECF4),
      surfaceDim = const Color(0xFF0A0C12),
      surfaceBright = const Color(0xFF252A38),
      surfaceContainerLowest = const Color(0xFF0A0C12),
      surfaceContainerLow = const Color(0xFF181B24),
      surfaceContainer = const Color(0xFF1F2330),
      surfaceContainerHigh = const Color(0xFF252A38),
      surfaceContainerHighest = const Color(0xFF2D3245),
      onSurfaceVariant = const Color(0xFF8B93A8),
      outline = const Color(0xFF252A38),
      outlineVariant = const Color(0xFF1F2330),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFFE8ECF4),
      onInverseSurface = const Color(0xFF0F1117),
      inversePrimary = const Color(0xFFEF5350),
      surfaceTint = const Color(0xFFEF5350),
      shimmer = const Color(0xFF1F2330),
      approval = const Color(0xFF4CAF79),
      hoverOverlay = const Color(0x14FFFFFF),
      pressedOverlay = const Color(0x21FFFFFF);

  /// Builds a full scheme from semantic colors (e.g. from [AppThemeExtension]).
  factory AppColorScheme.fromSemantic({
    required Color primary,
    required Color onPrimary,
    required Color surface,
    required Color onSurface,
    required Color surfaceVariant,
    required Color error,
    required Color onError,
    required Color hoverOverlay,
    required Color pressedOverlay,
    Color? divider,
  }) {
    final Color outline = divider ?? surfaceVariant;
    return AppColorScheme._(
      primary: primary,
      onPrimary: onPrimary,
      primaryContainer: primary.withAlpha(0x1A),
      onPrimaryContainer: onSurface,
      secondary: surfaceVariant,
      onSecondary: onSurface,
      secondaryContainer: surfaceVariant,
      onSecondaryContainer: onSurface,
      tertiary: primary,
      onTertiary: onPrimary,
      tertiaryContainer: primary.withAlpha(0x26),
      onTertiaryContainer: onSurface,
      error: error,
      onError: onError,
      errorContainer: error.withAlpha(0x1A),
      onErrorContainer: onError,
      surface: surface,
      onSurface: onSurface,
      surfaceDim: surface,
      surfaceBright: surface,
      surfaceContainerLowest: surface,
      surfaceContainerLow: surfaceVariant,
      surfaceContainer: surfaceVariant,
      surfaceContainerHigh: surfaceVariant,
      surfaceContainerHighest: surfaceVariant,
      onSurfaceVariant: onSurface.withAlpha(0xCC),
      outline: outline,
      outlineVariant: surfaceVariant,
      shadow: const Color(0xFF000000),
      scrim: const Color(0xFF000000),
      inverseSurface: onSurface,
      onInverseSurface: surface,
      inversePrimary: primary,
      surfaceTint: primary,
      shimmer: surfaceVariant,
      approval: const Color(0xFF22C55E),
      hoverOverlay: hoverOverlay,
      pressedOverlay: pressedOverlay,
    );
  }

  final Color primary;
  final Color onPrimary;
  final Color primaryContainer;
  final Color onPrimaryContainer;
  final Color secondary;
  final Color onSecondary;
  final Color secondaryContainer;
  final Color onSecondaryContainer;
  final Color tertiary;
  final Color onTertiary;
  final Color tertiaryContainer;
  final Color onTertiaryContainer;
  final Color error;
  final Color onError;
  final Color errorContainer;
  final Color onErrorContainer;
  final Color surface;
  final Color onSurface;
  final Color surfaceDim;
  final Color surfaceBright;
  final Color surfaceContainerLowest;
  final Color surfaceContainerLow;
  final Color surfaceContainer;
  final Color surfaceContainerHigh;
  final Color surfaceContainerHighest;
  final Color onSurfaceVariant;
  final Color outline;
  final Color outlineVariant;
  final Color shadow;
  final Color scrim;
  final Color inverseSurface;
  final Color onInverseSurface;
  final Color inversePrimary;
  final Color surfaceTint;
  final Color shimmer;
  final Color approval;
  final Color hoverOverlay;
  final Color pressedOverlay;

  @override
  AppColorScheme copyWith({
    Color? primary,
    Color? onPrimary,
    Color? primaryContainer,
    Color? onPrimaryContainer,
    Color? secondary,
    Color? onSecondary,
    Color? secondaryContainer,
    Color? onSecondaryContainer,
    Color? tertiary,
    Color? onTertiary,
    Color? tertiaryContainer,
    Color? onTertiaryContainer,
    Color? error,
    Color? onError,
    Color? errorContainer,
    Color? onErrorContainer,
    Color? surface,
    Color? onSurface,
    Color? surfaceDim,
    Color? surfaceBright,
    Color? surfaceContainerLowest,
    Color? surfaceContainerLow,
    Color? surfaceContainer,
    Color? surfaceContainerHigh,
    Color? surfaceContainerHighest,
    Color? onSurfaceVariant,
    Color? outline,
    Color? outlineVariant,
    Color? shadow,
    Color? scrim,
    Color? inverseSurface,
    Color? onInverseSurface,
    Color? inversePrimary,
    Color? surfaceTint,
    Color? shimmer,
    Color? approval,
    Color? hoverOverlay,
    Color? pressedOverlay,
  }) {
    return AppColorScheme._(
      primary: primary ?? this.primary,
      onPrimary: onPrimary ?? this.onPrimary,
      primaryContainer: primaryContainer ?? this.primaryContainer,
      onPrimaryContainer: onPrimaryContainer ?? this.onPrimaryContainer,
      secondary: secondary ?? this.secondary,
      onSecondary: onSecondary ?? this.onSecondary,
      secondaryContainer: secondaryContainer ?? this.secondaryContainer,
      onSecondaryContainer: onSecondaryContainer ?? this.onSecondaryContainer,
      tertiary: tertiary ?? this.tertiary,
      onTertiary: onTertiary ?? this.onTertiary,
      tertiaryContainer: tertiaryContainer ?? this.tertiaryContainer,
      onTertiaryContainer: onTertiaryContainer ?? this.onTertiaryContainer,
      error: error ?? this.error,
      onError: onError ?? this.onError,
      errorContainer: errorContainer ?? this.errorContainer,
      onErrorContainer: onErrorContainer ?? this.onErrorContainer,
      surface: surface ?? this.surface,
      onSurface: onSurface ?? this.onSurface,
      surfaceDim: surfaceDim ?? this.surfaceDim,
      surfaceBright: surfaceBright ?? this.surfaceBright,
      surfaceContainerLowest:
          surfaceContainerLowest ?? this.surfaceContainerLowest,
      surfaceContainerLow: surfaceContainerLow ?? this.surfaceContainerLow,
      surfaceContainer: surfaceContainer ?? this.surfaceContainer,
      surfaceContainerHigh: surfaceContainerHigh ?? this.surfaceContainerHigh,
      surfaceContainerHighest:
          surfaceContainerHighest ?? this.surfaceContainerHighest,
      onSurfaceVariant: onSurfaceVariant ?? this.onSurfaceVariant,
      outline: outline ?? this.outline,
      outlineVariant: outlineVariant ?? this.outlineVariant,
      shadow: shadow ?? this.shadow,
      scrim: scrim ?? this.scrim,
      inverseSurface: inverseSurface ?? this.inverseSurface,
      onInverseSurface: onInverseSurface ?? this.onInverseSurface,
      inversePrimary: inversePrimary ?? this.inversePrimary,
      surfaceTint: surfaceTint ?? this.surfaceTint,
      shimmer: shimmer ?? this.shimmer,
      approval: approval ?? this.approval,
      hoverOverlay: hoverOverlay ?? this.hoverOverlay,
      pressedOverlay: pressedOverlay ?? this.pressedOverlay,
    );
  }

  @override
  ThemeExtension<AppColorScheme> lerp(
    ThemeExtension<AppColorScheme>? other,
    double t,
  ) {
    if (other is! AppColorScheme) {
      return this;
    }

    return AppColorScheme._(
      primary: Color.lerp(primary, other.primary, t)!,
      onPrimary: Color.lerp(onPrimary, other.onPrimary, t)!,
      primaryContainer: Color.lerp(
        primaryContainer,
        other.primaryContainer,
        t,
      )!,
      onPrimaryContainer: Color.lerp(
        onPrimaryContainer,
        other.onPrimaryContainer,
        t,
      )!,
      secondary: Color.lerp(secondary, other.secondary, t)!,
      onSecondary: Color.lerp(onSecondary, other.onSecondary, t)!,
      secondaryContainer: Color.lerp(
        secondaryContainer,
        other.secondaryContainer,
        t,
      )!,
      onSecondaryContainer: Color.lerp(
        onSecondaryContainer,
        other.onSecondaryContainer,
        t,
      )!,
      tertiary: Color.lerp(tertiary, other.tertiary, t)!,
      onTertiary: Color.lerp(onTertiary, other.onTertiary, t)!,
      tertiaryContainer: Color.lerp(
        tertiaryContainer,
        other.tertiaryContainer,
        t,
      )!,
      onTertiaryContainer: Color.lerp(
        onTertiaryContainer,
        other.onTertiaryContainer,
        t,
      )!,
      error: Color.lerp(error, other.error, t)!,
      onError: Color.lerp(onError, other.onError, t)!,
      errorContainer: Color.lerp(errorContainer, other.errorContainer, t)!,
      onErrorContainer: Color.lerp(
        onErrorContainer,
        other.onErrorContainer,
        t,
      )!,
      surface: Color.lerp(surface, other.surface, t)!,
      onSurface: Color.lerp(onSurface, other.onSurface, t)!,
      surfaceDim: Color.lerp(surfaceDim, other.surfaceDim, t)!,
      surfaceBright: Color.lerp(surfaceBright, other.surfaceBright, t)!,
      surfaceContainerLowest: Color.lerp(
        surfaceContainerLowest,
        other.surfaceContainerLowest,
        t,
      )!,
      surfaceContainerLow: Color.lerp(
        surfaceContainerLow,
        other.surfaceContainerLow,
        t,
      )!,
      surfaceContainer: Color.lerp(
        surfaceContainer,
        other.surfaceContainer,
        t,
      )!,
      surfaceContainerHigh: Color.lerp(
        surfaceContainerHigh,
        other.surfaceContainerHigh,
        t,
      )!,
      surfaceContainerHighest: Color.lerp(
        surfaceContainerHighest,
        other.surfaceContainerHighest,
        t,
      )!,
      onSurfaceVariant: Color.lerp(
        onSurfaceVariant,
        other.onSurfaceVariant,
        t,
      )!,
      outline: Color.lerp(outline, other.outline, t)!,
      outlineVariant: Color.lerp(outlineVariant, other.outlineVariant, t)!,
      shadow: Color.lerp(shadow, other.shadow, t)!,
      scrim: Color.lerp(scrim, other.scrim, t)!,
      inverseSurface: Color.lerp(inverseSurface, other.inverseSurface, t)!,
      onInverseSurface: Color.lerp(
        onInverseSurface,
        other.onInverseSurface,
        t,
      )!,
      inversePrimary: Color.lerp(inversePrimary, other.inversePrimary, t)!,
      surfaceTint: Color.lerp(surfaceTint, other.surfaceTint, t)!,
      shimmer: Color.lerp(shimmer, other.shimmer, t)!,
      approval: Color.lerp(approval, other.approval, t)!,
      hoverOverlay: Color.lerp(hoverOverlay, other.hoverOverlay, t)!,
      pressedOverlay: Color.lerp(pressedOverlay, other.pressedOverlay, t)!,
    );
  }

  static AppColorScheme of(BuildContext context) =>
      Theme.of(context).extension<AppColorScheme>() ??
      _throwThemeExceptionFromFunc(context);
}

Never _throwThemeExceptionFromFunc(BuildContext context) =>
    throw Exception('$AppColorScheme not found in $context');
