import 'package:flutter/material.dart';

@immutable
class AppColorScheme extends ThemeExtension<AppColorScheme> {
  const AppColorScheme._({
    required this.primary,
    required this.onPrimary,
    required this.primaryContainer,
    required this.onPrimaryContainer,
    required this.secondary,
    required this.onSecondary,
    required this.secondaryContainer,
    required this.onSecondaryContainer,
    required this.tertiary,
    required this.onTertiary,
    required this.tertiaryContainer,
    required this.onTertiaryContainer,
    required this.error,
    required this.onError,
    required this.errorContainer,
    required this.onErrorContainer,
    required this.surface,
    required this.onSurface,
    required this.surfaceDim,
    required this.surfaceBright,
    required this.surfaceContainerLowest,
    required this.surfaceContainerLow,
    required this.surfaceContainer,
    required this.surfaceContainerHigh,
    required this.surfaceContainerHighest,
    required this.onSurfaceVariant,
    required this.outline,
    required this.outlineVariant,
    required this.shadow,
    required this.scrim,
    required this.inverseSurface,
    required this.onInverseSurface,
    required this.inversePrimary,
    required this.surfaceTint,
    required this.shimmer,
    required this.approval,
    required this.hoverOverlay,
    required this.pressedOverlay,
  });

  const AppColorScheme.light()
    : primary = const Color(0xFF7B1FA2),
      onPrimary = const Color(0xFFFFFFFF),
      primaryContainer = const Color(0xFFE1BEE7),
      onPrimaryContainer = const Color(0xFF4A148C),
      secondary = const Color(0xFFE5E5E5),
      onSecondary = const Color(0xFF111111),
      secondaryContainer = const Color(0xFFD0D0D0),
      onSecondaryContainer = const Color(0xFF111111),
      tertiary = const Color(0xFF7B1FA2),
      onTertiary = const Color(0xFFFFFFFF),
      tertiaryContainer = const Color(0xFFE1BEE7),
      onTertiaryContainer = const Color(0xFF4A148C),
      error = const Color(0xFFCC3333),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0xFFFFEBEB),
      onErrorContainer = const Color(0xFF7A0000),
      surface = const Color(0xFFF8F8F8),
      onSurface = const Color(0xFF111111),
      surfaceDim = const Color(0xFFE0E0E0),
      surfaceBright = const Color(0xFFFFFFFF),
      surfaceContainerLowest = const Color(0xFFFFFFFF),
      surfaceContainerLow = const Color(0xFFF2F2F2),
      surfaceContainer = const Color(0xFFE6E6E6),
      surfaceContainerHigh = const Color(0xFFD9D9D9),
      surfaceContainerHighest = const Color(0xFFCCCCCC),
      onSurfaceVariant = const Color(0xFF666666),
      outline = const Color(0xFFD0D0D0),
      outlineVariant = const Color(0xFFE0E0E0),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFF111111),
      onInverseSurface = const Color(0xFFF5F5F5),
      inversePrimary = const Color(0xFFE1BEE7),
      surfaceTint = const Color(0xFF7B1FA2),
      shimmer = const Color(0xFFE5E5E5),
      approval = const Color(0xFF777777),
      hoverOverlay = const Color(0x0D000000),
      pressedOverlay = const Color(0x1A000000);

  const AppColorScheme.dark()
    : primary = const Color(0xFFCE93D8),
      onPrimary = const Color(0xFF4A148C),
      primaryContainer = const Color(0xFF6A1B9A),
      onPrimaryContainer = const Color(0xFFE1BEE7),
      secondary = const Color(0xFF252525),
      onSecondary = const Color(0xFFF0F0F0),
      secondaryContainer = const Color(0xFF3A3A3A),
      onSecondaryContainer = const Color(0xFFF0F0F0),
      tertiary = const Color(0xFFCE93D8),
      onTertiary = const Color(0xFF4A148C),
      tertiaryContainer = const Color(0xFF6A1B9A),
      onTertiaryContainer = const Color(0xFFE1BEE7),
      error = const Color(0xFFFF6B6B),
      onError = const Color(0xFF1A0000),
      errorContainer = const Color(0xFF5C1515),
      onErrorContainer = const Color(0xFFFFCDD2),
      surface = const Color(0xFF111111),
      onSurface = const Color(0xFFF5F5F5),
      surfaceDim = const Color(0xFF0E0E0E),
      surfaceBright = const Color(0xFF272727),
      surfaceContainerLowest = const Color(0xFF000000),
      surfaceContainerLow = const Color(0xFF1E1E1E),
      surfaceContainer = const Color(0xFF262626),
      surfaceContainerHigh = const Color(0xFF2E2E2E),
      surfaceContainerHighest = const Color(0xFF3A3A3A),
      onSurfaceVariant = const Color(0xFFB0B0B0),
      outline = const Color(0xFF555555),
      outlineVariant = const Color(0xFF2A2A2A),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFFF5F5F5),
      onInverseSurface = const Color(0xFF111111),
      inversePrimary = const Color(0xFF4A148C),
      surfaceTint = const Color(0xFFCE93D8),
      shimmer = const Color(0xFF2A2A2A),
      approval = const Color(0xFF777777),
      hoverOverlay = const Color(0x14000000),
      pressedOverlay = const Color(0x21000000);

  // --- Light Blue (accent 1) ---
  const AppColorScheme.lightBlue()
    : primary = const Color(0xFF1976D2),
      onPrimary = const Color(0xFFFFFFFF),
      primaryContainer = const Color(0xFFBBDEFB),
      onPrimaryContainer = const Color(0xFF0D47A1),
      secondary = const Color(0xFFE5E5E5),
      onSecondary = const Color(0xFF111111),
      secondaryContainer = const Color(0xFFD0D0D0),
      onSecondaryContainer = const Color(0xFF111111),
      tertiary = const Color(0xFF1976D2),
      onTertiary = const Color(0xFFFFFFFF),
      tertiaryContainer = const Color(0xFFBBDEFB),
      onTertiaryContainer = const Color(0xFF0D47A1),
      error = const Color(0xFFCC3333),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0xFFFFEBEB),
      onErrorContainer = const Color(0xFF7A0000),
      surface = const Color(0xFFF8F8F8),
      onSurface = const Color(0xFF111111),
      surfaceDim = const Color(0xFFE0E0E0),
      surfaceBright = const Color(0xFFFFFFFF),
      surfaceContainerLowest = const Color(0xFFFFFFFF),
      surfaceContainerLow = const Color(0xFFF2F2F2),
      surfaceContainer = const Color(0xFFE6E6E6),
      surfaceContainerHigh = const Color(0xFFD9D9D9),
      surfaceContainerHighest = const Color(0xFFCCCCCC),
      onSurfaceVariant = const Color(0xFF666666),
      outline = const Color(0xFFD0D0D0),
      outlineVariant = const Color(0xFFE0E0E0),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFF111111),
      onInverseSurface = const Color(0xFFF5F5F5),
      inversePrimary = const Color(0xFFBBDEFB),
      surfaceTint = const Color(0xFF1976D2),
      shimmer = const Color(0xFFE5E5E5),
      approval = const Color(0xFF777777),
      hoverOverlay = const Color(0x0D000000),
      pressedOverlay = const Color(0x1A000000);

  // --- Light Green (accent 2) ---
  const AppColorScheme.lightGreen()
    : primary = const Color(0xFF2E7D32),
      onPrimary = const Color(0xFFFFFFFF),
      primaryContainer = const Color(0xFFC8E6C9),
      onPrimaryContainer = const Color(0xFF1B5E20),
      secondary = const Color(0xFFE5E5E5),
      onSecondary = const Color(0xFF111111),
      secondaryContainer = const Color(0xFFD0D0D0),
      onSecondaryContainer = const Color(0xFF111111),
      tertiary = const Color(0xFF2E7D32),
      onTertiary = const Color(0xFFFFFFFF),
      tertiaryContainer = const Color(0xFFC8E6C9),
      onTertiaryContainer = const Color(0xFF1B5E20),
      error = const Color(0xFFCC3333),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0xFFFFEBEB),
      onErrorContainer = const Color(0xFF7A0000),
      surface = const Color(0xFFF8F8F8),
      onSurface = const Color(0xFF111111),
      surfaceDim = const Color(0xFFE0E0E0),
      surfaceBright = const Color(0xFFFFFFFF),
      surfaceContainerLowest = const Color(0xFFFFFFFF),
      surfaceContainerLow = const Color(0xFFF2F2F2),
      surfaceContainer = const Color(0xFFE6E6E6),
      surfaceContainerHigh = const Color(0xFFD9D9D9),
      surfaceContainerHighest = const Color(0xFFCCCCCC),
      onSurfaceVariant = const Color(0xFF666666),
      outline = const Color(0xFFD0D0D0),
      outlineVariant = const Color(0xFFE0E0E0),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFF111111),
      onInverseSurface = const Color(0xFFF5F5F5),
      inversePrimary = const Color(0xFFC8E6C9),
      surfaceTint = const Color(0xFF2E7D32),
      shimmer = const Color(0xFFE5E5E5),
      approval = const Color(0xFF777777),
      hoverOverlay = const Color(0x0D000000),
      pressedOverlay = const Color(0x1A000000);

  // --- Light Purple (accent 3) ---
  const AppColorScheme.lightPurple()
    : primary = const Color(0xFF7B1FA2),
      onPrimary = const Color(0xFFFFFFFF),
      primaryContainer = const Color(0xFFE1BEE7),
      onPrimaryContainer = const Color(0xFF4A148C),
      secondary = const Color(0xFFE5E5E5),
      onSecondary = const Color(0xFF111111),
      secondaryContainer = const Color(0xFFD0D0D0),
      onSecondaryContainer = const Color(0xFF111111),
      tertiary = const Color(0xFF7B1FA2),
      onTertiary = const Color(0xFFFFFFFF),
      tertiaryContainer = const Color(0xFFE1BEE7),
      onTertiaryContainer = const Color(0xFF4A148C),
      error = const Color(0xFFCC3333),
      onError = const Color(0xFFFFFFFF),
      errorContainer = const Color(0xFFFFEBEB),
      onErrorContainer = const Color(0xFF7A0000),
      surface = const Color(0xFFF8F8F8),
      onSurface = const Color(0xFF111111),
      surfaceDim = const Color(0xFFE0E0E0),
      surfaceBright = const Color(0xFFFFFFFF),
      surfaceContainerLowest = const Color(0xFFFFFFFF),
      surfaceContainerLow = const Color(0xFFF2F2F2),
      surfaceContainer = const Color(0xFFE6E6E6),
      surfaceContainerHigh = const Color(0xFFD9D9D9),
      surfaceContainerHighest = const Color(0xFFCCCCCC),
      onSurfaceVariant = const Color(0xFF666666),
      outline = const Color(0xFFD0D0D0),
      outlineVariant = const Color(0xFFE0E0E0),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFF111111),
      onInverseSurface = const Color(0xFFF5F5F5),
      inversePrimary = const Color(0xFFE1BEE7),
      surfaceTint = const Color(0xFF7B1FA2),
      shimmer = const Color(0xFFE5E5E5),
      approval = const Color(0xFF777777),
      hoverOverlay = const Color(0x0D000000),
      pressedOverlay = const Color(0x1A000000);

  // --- Dark Blue (accent 1) ---
  const AppColorScheme.darkBlue()
    : primary = const Color(0xFF90CAF9),
      onPrimary = const Color(0xFF0D47A1),
      primaryContainer = const Color(0xFF1565C0),
      onPrimaryContainer = const Color(0xFFBBDEFB),
      secondary = const Color(0xFF252525),
      onSecondary = const Color(0xFFF0F0F0),
      secondaryContainer = const Color(0xFF3A3A3A),
      onSecondaryContainer = const Color(0xFFF0F0F0),
      tertiary = const Color(0xFF90CAF9),
      onTertiary = const Color(0xFF0D47A1),
      tertiaryContainer = const Color(0xFF1565C0),
      onTertiaryContainer = const Color(0xFFBBDEFB),
      error = const Color(0xFFFF6B6B),
      onError = const Color(0xFF1A0000),
      errorContainer = const Color(0xFF5C1515),
      onErrorContainer = const Color(0xFFFFCDD2),
      surface = const Color(0xFF111111),
      onSurface = const Color(0xFFF5F5F5),
      surfaceDim = const Color(0xFF0E0E0E),
      surfaceBright = const Color(0xFF272727),
      surfaceContainerLowest = const Color(0xFF000000),
      surfaceContainerLow = const Color(0xFF1E1E1E),
      surfaceContainer = const Color(0xFF262626),
      surfaceContainerHigh = const Color(0xFF2E2E2E),
      surfaceContainerHighest = const Color(0xFF3A3A3A),
      onSurfaceVariant = const Color(0xFFB0B0B0),
      outline = const Color(0xFF555555),
      outlineVariant = const Color(0xFF2A2A2A),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFFF5F5F5),
      onInverseSurface = const Color(0xFF111111),
      inversePrimary = const Color(0xFF0D47A1),
      surfaceTint = const Color(0xFF90CAF9),
      shimmer = const Color(0xFF2A2A2A),
      approval = const Color(0xFF777777),
      hoverOverlay = const Color(0x14000000),
      pressedOverlay = const Color(0x21000000);

  // --- Dark Green (accent 2) ---
  const AppColorScheme.darkGreen()
    : primary = const Color(0xFF81C784),
      onPrimary = const Color(0xFF1B5E20),
      primaryContainer = const Color(0xFF388E3C),
      onPrimaryContainer = const Color(0xFFC8E6C9),
      secondary = const Color(0xFF252525),
      onSecondary = const Color(0xFFF0F0F0),
      secondaryContainer = const Color(0xFF3A3A3A),
      onSecondaryContainer = const Color(0xFFF0F0F0),
      tertiary = const Color(0xFF81C784),
      onTertiary = const Color(0xFF1B5E20),
      tertiaryContainer = const Color(0xFF388E3C),
      onTertiaryContainer = const Color(0xFFC8E6C9),
      error = const Color(0xFFFF6B6B),
      onError = const Color(0xFF1A0000),
      errorContainer = const Color(0xFF5C1515),
      onErrorContainer = const Color(0xFFFFCDD2),
      surface = const Color(0xFF111111),
      onSurface = const Color(0xFFF5F5F5),
      surfaceDim = const Color(0xFF0E0E0E),
      surfaceBright = const Color(0xFF272727),
      surfaceContainerLowest = const Color(0xFF000000),
      surfaceContainerLow = const Color(0xFF1E1E1E),
      surfaceContainer = const Color(0xFF262626),
      surfaceContainerHigh = const Color(0xFF2E2E2E),
      surfaceContainerHighest = const Color(0xFF3A3A3A),
      onSurfaceVariant = const Color(0xFFB0B0B0),
      outline = const Color(0xFF555555),
      outlineVariant = const Color(0xFF2A2A2A),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFFF5F5F5),
      onInverseSurface = const Color(0xFF111111),
      inversePrimary = const Color(0xFF1B5E20),
      surfaceTint = const Color(0xFF81C784),
      shimmer = const Color(0xFF2A2A2A),
      approval = const Color(0xFF777777),
      hoverOverlay = const Color(0x14000000),
      pressedOverlay = const Color(0x21000000);

  // --- Dark Purple (accent 3) ---
  const AppColorScheme.darkPurple()
    : primary = const Color(0xFFCE93D8),
      onPrimary = const Color(0xFF4A148C),
      primaryContainer = const Color(0xFF6A1B9A),
      onPrimaryContainer = const Color(0xFFE1BEE7),
      secondary = const Color(0xFF252525),
      onSecondary = const Color(0xFFF0F0F0),
      secondaryContainer = const Color(0xFF3A3A3A),
      onSecondaryContainer = const Color(0xFFF0F0F0),
      tertiary = const Color(0xFFCE93D8),
      onTertiary = const Color(0xFF4A148C),
      tertiaryContainer = const Color(0xFF6A1B9A),
      onTertiaryContainer = const Color(0xFFE1BEE7),
      error = const Color(0xFFFF6B6B),
      onError = const Color(0xFF1A0000),
      errorContainer = const Color(0xFF5C1515),
      onErrorContainer = const Color(0xFFFFCDD2),
      surface = const Color(0xFF111111),
      onSurface = const Color(0xFFF5F5F5),
      surfaceDim = const Color(0xFF0E0E0E),
      surfaceBright = const Color(0xFF272727),
      surfaceContainerLowest = const Color(0xFF000000),
      surfaceContainerLow = const Color(0xFF1E1E1E),
      surfaceContainer = const Color(0xFF262626),
      surfaceContainerHigh = const Color(0xFF2E2E2E),
      surfaceContainerHighest = const Color(0xFF3A3A3A),
      onSurfaceVariant = const Color(0xFFB0B0B0),
      outline = const Color(0xFF555555),
      outlineVariant = const Color(0xFF2A2A2A),
      shadow = const Color(0xFF000000),
      scrim = const Color(0xFF000000),
      inverseSurface = const Color(0xFFF5F5F5),
      onInverseSurface = const Color(0xFF111111),
      inversePrimary = const Color(0xFF4A148C),
      surfaceTint = const Color(0xFFCE93D8),
      shimmer = const Color(0xFF2A2A2A),
      approval = const Color(0xFF777777),
      hoverOverlay = const Color(0x14000000),
      pressedOverlay = const Color(0x21000000);

  /// Builds a full scheme from semantic colors (e.g. from [AppThemeExtension]).
  factory AppColorScheme.fromSemantic({
    required Color primary,
    required Color onPrimary,
    required Color surface,
    required Color onSurface,
    required Color surfaceVariant,
    required Color error,
    required Color onError,
    required Color hoverOverlay,
    required Color pressedOverlay,
    Color? divider,
  }) {
    final Color outline = divider ?? surfaceVariant;
    return AppColorScheme._(
      primary: primary,
      onPrimary: onPrimary,
      primaryContainer: primary.withAlpha(0x1A),
      onPrimaryContainer: onSurface,
      secondary: surfaceVariant,
      onSecondary: onSurface,
      secondaryContainer: surfaceVariant,
      onSecondaryContainer: onSurface,
      tertiary: primary,
      onTertiary: onPrimary,
      tertiaryContainer: primary.withAlpha(0x26),
      onTertiaryContainer: onSurface,
      error: error,
      onError: onError,
      errorContainer: error.withAlpha(0x1A),
      onErrorContainer: onError,
      surface: surface,
      onSurface: onSurface,
      surfaceDim: surface,
      surfaceBright: surface,
      surfaceContainerLowest: surface,
      surfaceContainerLow: surfaceVariant,
      surfaceContainer: surfaceVariant,
      surfaceContainerHigh: surfaceVariant,
      surfaceContainerHighest: surfaceVariant,
      onSurfaceVariant: onSurface.withAlpha(0xCC),
      outline: outline,
      outlineVariant: surfaceVariant,
      shadow: const Color(0xFF000000),
      scrim: const Color(0xFF000000),
      inverseSurface: onSurface,
      onInverseSurface: surface,
      inversePrimary: primary,
      surfaceTint: primary,
      shimmer: surfaceVariant,
      approval: const Color(0xFF22C55E),
      hoverOverlay: hoverOverlay,
      pressedOverlay: pressedOverlay,
    );
  }

  final Color primary;
  final Color onPrimary;
  final Color primaryContainer;
  final Color onPrimaryContainer;
  final Color secondary;
  final Color onSecondary;
  final Color secondaryContainer;
  final Color onSecondaryContainer;
  final Color tertiary;
  final Color onTertiary;
  final Color tertiaryContainer;
  final Color onTertiaryContainer;
  final Color error;
  final Color onError;
  final Color errorContainer;
  final Color onErrorContainer;
  final Color surface;
  final Color onSurface;
  final Color surfaceDim;
  final Color surfaceBright;
  final Color surfaceContainerLowest;
  final Color surfaceContainerLow;
  final Color surfaceContainer;
  final Color surfaceContainerHigh;
  final Color surfaceContainerHighest;
  final Color onSurfaceVariant;
  final Color outline;
  final Color outlineVariant;
  final Color shadow;
  final Color scrim;
  final Color inverseSurface;
  final Color onInverseSurface;
  final Color inversePrimary;
  final Color surfaceTint;
  final Color shimmer;
  final Color approval;
  final Color hoverOverlay;
  final Color pressedOverlay;

  @override
  AppColorScheme copyWith({
    Color? primary,
    Color? onPrimary,
    Color? primaryContainer,
    Color? onPrimaryContainer,
    Color? secondary,
    Color? onSecondary,
    Color? secondaryContainer,
    Color? onSecondaryContainer,
    Color? tertiary,
    Color? onTertiary,
    Color? tertiaryContainer,
    Color? onTertiaryContainer,
    Color? error,
    Color? onError,
    Color? errorContainer,
    Color? onErrorContainer,
    Color? surface,
    Color? onSurface,
    Color? surfaceDim,
    Color? surfaceBright,
    Color? surfaceContainerLowest,
    Color? surfaceContainerLow,
    Color? surfaceContainer,
    Color? surfaceContainerHigh,
    Color? surfaceContainerHighest,
    Color? onSurfaceVariant,
    Color? outline,
    Color? outlineVariant,
    Color? shadow,
    Color? scrim,
    Color? inverseSurface,
    Color? onInverseSurface,
    Color? inversePrimary,
    Color? surfaceTint,
    Color? shimmer,
    Color? approval,
    Color? hoverOverlay,
    Color? pressedOverlay,
  }) {
    return AppColorScheme._(
      primary: primary ?? this.primary,
      onPrimary: onPrimary ?? this.onPrimary,
      primaryContainer: primaryContainer ?? this.primaryContainer,
      onPrimaryContainer: onPrimaryContainer ?? this.onPrimaryContainer,
      secondary: secondary ?? this.secondary,
      onSecondary: onSecondary ?? this.onSecondary,
      secondaryContainer: secondaryContainer ?? this.secondaryContainer,
      onSecondaryContainer: onSecondaryContainer ?? this.onSecondaryContainer,
      tertiary: tertiary ?? this.tertiary,
      onTertiary: onTertiary ?? this.onTertiary,
      tertiaryContainer: tertiaryContainer ?? this.tertiaryContainer,
      onTertiaryContainer: onTertiaryContainer ?? this.onTertiaryContainer,
      error: error ?? this.error,
      onError: onError ?? this.onError,
      errorContainer: errorContainer ?? this.errorContainer,
      onErrorContainer: onErrorContainer ?? this.onErrorContainer,
      surface: surface ?? this.surface,
      onSurface: onSurface ?? this.onSurface,
      surfaceDim: surfaceDim ?? this.surfaceDim,
      surfaceBright: surfaceBright ?? this.surfaceBright,
      surfaceContainerLowest:
          surfaceContainerLowest ?? this.surfaceContainerLowest,
      surfaceContainerLow: surfaceContainerLow ?? this.surfaceContainerLow,
      surfaceContainer: surfaceContainer ?? this.surfaceContainer,
      surfaceContainerHigh: surfaceContainerHigh ?? this.surfaceContainerHigh,
      surfaceContainerHighest:
          surfaceContainerHighest ?? this.surfaceContainerHighest,
      onSurfaceVariant: onSurfaceVariant ?? this.onSurfaceVariant,
      outline: outline ?? this.outline,
      outlineVariant: outlineVariant ?? this.outlineVariant,
      shadow: shadow ?? this.shadow,
      scrim: scrim ?? this.scrim,
      inverseSurface: inverseSurface ?? this.inverseSurface,
      onInverseSurface: onInverseSurface ?? this.onInverseSurface,
      inversePrimary: inversePrimary ?? this.inversePrimary,
      surfaceTint: surfaceTint ?? this.surfaceTint,
      shimmer: shimmer ?? this.shimmer,
      approval: approval ?? this.approval,
      hoverOverlay: hoverOverlay ?? this.hoverOverlay,
      pressedOverlay: pressedOverlay ?? this.pressedOverlay,
    );
  }

  @override
  ThemeExtension<AppColorScheme> lerp(
    ThemeExtension<AppColorScheme>? other,
    double t,
  ) {
    if (other is! AppColorScheme) {
      return this;
    }

    return AppColorScheme._(
      primary: Color.lerp(primary, other.primary, t)!,
      onPrimary: Color.lerp(onPrimary, other.onPrimary, t)!,
      primaryContainer: Color.lerp(
        primaryContainer,
        other.primaryContainer,
        t,
      )!,
      onPrimaryContainer: Color.lerp(
        onPrimaryContainer,
        other.onPrimaryContainer,
        t,
      )!,
      secondary: Color.lerp(secondary, other.secondary, t)!,
      onSecondary: Color.lerp(onSecondary, other.onSecondary, t)!,
      secondaryContainer: Color.lerp(
        secondaryContainer,
        other.secondaryContainer,
        t,
      )!,
      onSecondaryContainer: Color.lerp(
        onSecondaryContainer,
        other.onSecondaryContainer,
        t,
      )!,
      tertiary: Color.lerp(tertiary, other.tertiary, t)!,
      onTertiary: Color.lerp(onTertiary, other.onTertiary, t)!,
      tertiaryContainer: Color.lerp(
        tertiaryContainer,
        other.tertiaryContainer,
        t,
      )!,
      onTertiaryContainer: Color.lerp(
        onTertiaryContainer,
        other.onTertiaryContainer,
        t,
      )!,
      error: Color.lerp(error, other.error, t)!,
      onError: Color.lerp(onError, other.onError, t)!,
      errorContainer: Color.lerp(errorContainer, other.errorContainer, t)!,
      onErrorContainer: Color.lerp(
        onErrorContainer,
        other.onErrorContainer,
        t,
      )!,
      surface: Color.lerp(surface, other.surface, t)!,
      onSurface: Color.lerp(onSurface, other.onSurface, t)!,
      surfaceDim: Color.lerp(surfaceDim, other.surfaceDim, t)!,
      surfaceBright: Color.lerp(surfaceBright, other.surfaceBright, t)!,
      surfaceContainerLowest: Color.lerp(
        surfaceContainerLowest,
        other.surfaceContainerLowest,
        t,
      )!,
      surfaceContainerLow: Color.lerp(
        surfaceContainerLow,
        other.surfaceContainerLow,
        t,
      )!,
      surfaceContainer: Color.lerp(
        surfaceContainer,
        other.surfaceContainer,
        t,
      )!,
      surfaceContainerHigh: Color.lerp(
        surfaceContainerHigh,
        other.surfaceContainerHigh,
        t,
      )!,
      surfaceContainerHighest: Color.lerp(
        surfaceContainerHighest,
        other.surfaceContainerHighest,
        t,
      )!,
      onSurfaceVariant: Color.lerp(
        onSurfaceVariant,
        other.onSurfaceVariant,
        t,
      )!,
      outline: Color.lerp(outline, other.outline, t)!,
      outlineVariant: Color.lerp(outlineVariant, other.outlineVariant, t)!,
      shadow: Color.lerp(shadow, other.shadow, t)!,
      scrim: Color.lerp(scrim, other.scrim, t)!,
      inverseSurface: Color.lerp(inverseSurface, other.inverseSurface, t)!,
      onInverseSurface: Color.lerp(
        onInverseSurface,
        other.onInverseSurface,
        t,
      )!,
      inversePrimary: Color.lerp(inversePrimary, other.inversePrimary, t)!,
      surfaceTint: Color.lerp(surfaceTint, other.surfaceTint, t)!,
      shimmer: Color.lerp(shimmer, other.shimmer, t)!,
      approval: Color.lerp(approval, other.approval, t)!,
      hoverOverlay: Color.lerp(hoverOverlay, other.hoverOverlay, t)!,
      pressedOverlay: Color.lerp(pressedOverlay, other.pressedOverlay, t)!,
    );
  }

  static AppColorScheme of(BuildContext context) =>
      Theme.of(context).extension<AppColorScheme>() ??
      _throwThemeExceptionFromFunc(context);
}

Never _throwThemeExceptionFromFunc(BuildContext context) =>
    throw Exception('$AppColorScheme not found in $context');
